#pragma once
#include <Poco/Net/HTTPRequestHandler.h>
#include <Poco/Net/HTTPRequestHandlerFactory.h>
#include <Poco/Net/HTTPServerRequest.h>
#include <Poco/Net/HTTPServerResponse.h>
#include <Poco/Net/HTTPStream.h>
#include <Poco/Util/ServerApplication.h>
#include <Poco/Util/OptionSet.h>
#include <Poco/Dynamic/Var.h>
#include <Poco/JSON/JSON.h>
#include <Poco/JSON/Parser.h>
#include <Poco/JSON/Object.h>

#include <Poco/Net/HTTPServer.h>
#include <Poco/Net/ServerSocket.h>
#include <Poco/Net/HTTPServerParams.h>
#include <Poco/Util/Option.h>
#include <Poco/Util/HelpFormatter.h>
#include <Poco/JSON/JSON.h>
#include <Poco/UUIDGenerator.h>
#include <Poco/UUID.h>
#include <Poco/MD5Engine.h>
#include <Poco/Encodings.h>
#include <Poco/URI.h>
#include<Poco/Exception.h>

using Poco::BadCastException;
using Poco::InvalidAccessException;
using Poco::Exception;
using Poco::URI;
using Poco::MD5Engine;
using Poco::UUID;
using Poco::UUIDGenerator;
using Poco::Net::HTTPServer;
using Poco::Net::ServerSocket;
using Poco::Net::HTTPServerParams;
using Poco::Util::Option;
using Poco::Util::OptionCallback;
using Poco::Util::HelpFormatter;
using Poco::JSON::Parser;
using Poco::JSON::ParseHandler;
using Poco::JSON::Object;
using Poco::JSON::Array;
using Poco::Dynamic::Var;
using Poco::Net::HTTPRequestHandler;
using Poco::Net::HTTPRequestHandlerFactory;
using Poco::Net::HTTPServerRequest;
using Poco::Net::HTTPServerResponse;
using Poco::Net::HTTPBasicStreamBuf;
using Poco::Util::ServerApplication;
using Poco::Util::Application;
using Poco::Util::OptionSet;

#include <map>
#include <string>
#include <vector>
#include <stdexcept>
#include <iostream>
